### ISSUE TITLE
Suggestion on folder structure 

### ISSUE THREAD

**Issue by kharatps02** [CKGrafico/Cordova-Multiplatform-Template#30]
I have suggestion on typescript source code structure,It should have all TS and typing source code into one script folder so it will easily readable/understand. 
e.g.
- scripts
 - typings
 - modules
 - other folder
 
To that effect, need to update gulp tasks accordingly.

**Comment by CKGrafico** [comment]
I'm thinking about to change the folder structure for the version 2.0 of the template, but not sure about this structure because inside modules you will find .html files.
On my new project I'm following something like this:
- app
  - modules
    - module1
        - controllers
        - directives
        - templates
        - module1-module.ts
  - styles
     - fonts
     - images
     - vendor
     - scssComponent1
     - scssComponent2
- typings
- node_modules

But probably we can improve that
